table fat_vendas
	lineageTag: 05984bdd-6893-4661-981e-edd6358f40d8

	column cd_venda
		dataType: double
		formatString: 0
		lineageTag: e708fe89-d0f5-4e66-80b0-6e39ce548af2
		summarizeBy: sum
		sourceColumn: cd_venda

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column dt_venda
		dataType: dateTime
		formatString: Short Date
		lineageTag: 4455239d-9e4e-4881-8a66-9bf44abaac66
		summarizeBy: none
		sourceColumn: dt_venda

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column hr_vendas
		dataType: dateTime
		formatString: Long Time
		lineageTag: d7ceb536-922d-49eb-9e0e-c0680bb03485
		summarizeBy: none
		sourceColumn: hr_vendas

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column cd_vendedor
		dataType: int64
		formatString: 0
		lineageTag: 1a6e3279-700a-462c-a891-51f8a7bafe8d
		summarizeBy: sum
		sourceColumn: cd_vendedor

		annotation SummarizationSetBy = Automatic

	column cd_cliente
		dataType: int64
		formatString: 0
		lineageTag: dfe26b2b-bf6c-4111-9efd-51619122fe48
		summarizeBy: sum
		sourceColumn: cd_cliente

		annotation SummarizationSetBy = Automatic

	column idPlanoVenda
		dataType: int64
		formatString: 0
		lineageTag: e8e89b63-1f20-4d28-9d8f-e140b135b4e8
		summarizeBy: none
		sourceColumn: idPlanoVenda

		annotation SummarizationSetBy = Automatic

	column cd_produto
		dataType: double
		lineageTag: fb8ffe59-e5a7-4e2f-8223-3e8c86657d16
		summarizeBy: sum
		sourceColumn: cd_produto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column qtd_venda
		dataType: double
		lineageTag: 7ed5343b-b99a-47c2-aee3-14c4e3fb9d07
		summarizeBy: sum
		sourceColumn: qtd_venda

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column vlr_custo
		dataType: double
		lineageTag: eebee9a5-9444-42a6-b33e-8839cf607722
		summarizeBy: sum
		sourceColumn: vlr_custo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column vlr_venda
		dataType: double
		lineageTag: a2e50af5-ff41-4203-883f-de5eb7515b9c
		summarizeBy: sum
		sourceColumn: vlr_venda

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column vlr_desconto
		dataType: double
		lineageTag: 7e1b0f91-2293-43c0-89b2-aae8aa62ddc2
		summarizeBy: sum
		sourceColumn: vlr_desconto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column vlr_venda_total
		dataType: double
		lineageTag: be5ae285-a236-4684-8f07-befeff3e8818
		summarizeBy: sum
		sourceColumn: vlr_venda_total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ds_sistema
		dataType: string
		lineageTag: caf546bf-57c4-4dba-a605-21bad6b77321
		summarizeBy: none
		sourceColumn: ds_sistema

		annotation SummarizationSetBy = Automatic

	column dt_hr_venda
		dataType: dateTime
		formatString: General Date
		lineageTag: a9a31052-48a6-4f38-9fab-7f66c8d784d1
		summarizeBy: none
		sourceColumn: dt_hr_venda

		variation Variation
			isDefault
			relationship: 503e1a33-3401-4983-981b-947e8bee1c73
			defaultHierarchy: LocalDateTable_2fc1c74e-0907-4687-b98e-60cb264ba7fc.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column id_produto
		dataType: string
		lineageTag: 6c91d8d3-c131-41ee-9281-0c9aa51708aa
		summarizeBy: none
		sourceColumn: id_produto

		annotation SummarizationSetBy = Automatic

	column id_vendedor
		dataType: string
		lineageTag: 086f8def-e386-4604-bc13-1bf245ced206
		summarizeBy: none
		sourceColumn: id_vendedor

		annotation SummarizationSetBy = Automatic

	column id_cliente
		dataType: string
		lineageTag: f94e1722-cfe2-4c43-a406-80d618fa18e0
		summarizeBy: none
		sourceColumn: id_cliente

		annotation SummarizationSetBy = Automatic

	partition fat_vendas = m
		mode: import
		source =
				let
				    Fonte = PowerPlatform.Dataflows(null),
				    Workspaces = Fonte{[Id="Workspaces"]}[Data],
				    #"3302bffe-37e3-48cf-8e61-0e1eba5f63ce" = Workspaces{[workspaceId="3302bffe-37e3-48cf-8e61-0e1eba5f63ce"]}[Data],
				    #"0e903939-a26b-42c1-9cc2-baebc4f5b136" = #"3302bffe-37e3-48cf-8e61-0e1eba5f63ce"{[dataflowId="0e903939-a26b-42c1-9cc2-baebc4f5b136"]}[Data],
				    fat_vendas_ = #"0e903939-a26b-42c1-9cc2-baebc4f5b136"{[entity="fat_vendas",version=""]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(fat_vendas_,{{"cd_produto", Int64.Type}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Tipo Alterado", "id_produto", each Text.From([cd_produto]) & Text.From([ds_sistema])),
				    #"Linhas Classificadas" = Table.Sort(#"Personalização Adicionada",{{"dt_venda", Order.Descending}}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Linhas Classificadas",{{"dt_venda", type date}, {"cd_produto", type number}}),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Tipo Alterado1", "dt_hr_venda", each Text.From([dt_venda])&" "&Text.From([hr_vendas])),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Personalização Adicionada1",{{"dt_hr_venda", type datetime}}),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Tipo Alterado2",{"cd_venda", "dt_venda", "hr_vendas", "cd_vendedor", "cd_cliente", "idPlanoVenda", "cd_produto", "qtd_venda", "vlr_custo", "vlr_venda", "vlr_desconto", "vlr_venda_total", "ds_sistema", "dt_hr_venda", "id_produto"}),
				    #"Personalização Adicionada2" = Table.AddColumn(#"Colunas Reordenadas", "id_vendedor", each Text.From([cd_vendedor]) & Text.From([ds_sistema])),
				    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Personalização Adicionada2",{{"id_vendedor", type text}, {"id_produto", type text}}),
				    #"Personalização Adicionada3" = Table.AddColumn(#"Tipo Alterado3", "id_cliente", each Text.From([cd_cliente]) & Text.From([ds_sistema])),
				    #"Tipo Alterado4" = Table.TransformColumnTypes(#"Personalização Adicionada3",{{"id_cliente", type text}})
				in
				    #"Tipo Alterado4"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

