table fat_livro_caixa
	lineageTag: aa571b37-e1cf-4080-9277-664549734aa8

	column dt_lancamento
		dataType: dateTime
		formatString: Long Date
		lineageTag: d48108c0-82ec-4d43-8a48-ad5cce1b553f
		summarizeBy: none
		sourceColumn: dt_lancamento

		variation Variation
			isDefault
			relationship: 983845a4-62e2-4a8e-8d73-e8d14faf16f2
			defaultHierarchy: LocalDateTable_57b29106-cb59-4718-be77-613157c03e65.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column hr_lancamento
		dataType: dateTime
		formatString: Long Time
		lineageTag: a660b281-2916-4b70-97ce-d522847e4c05
		summarizeBy: none
		sourceColumn: hr_lancamento

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column tipo
		dataType: string
		lineageTag: e48b1d7f-0588-41de-95e0-6d2a8b06604e
		summarizeBy: none
		sourceColumn: tipo

		annotation SummarizationSetBy = Automatic

	column ds_sistema
		dataType: string
		lineageTag: 94d1e2a1-25ed-4155-a358-466784e6d956
		summarizeBy: none
		sourceColumn: ds_sistema

		annotation SummarizationSetBy = Automatic

	column dt_hr_lancamento
		dataType: dateTime
		formatString: General Date
		lineageTag: 7c84e742-5758-452b-b687-55603b2b712a
		summarizeBy: none
		sourceColumn: dt_hr_lancamento

		variation Variation
			isDefault
			relationship: 82e15716-9a23-480f-9775-9bbce4624b76
			defaultHierarchy: LocalDateTable_b3415495-e46c-4d04-9cfb-d06b6509e6ba.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column cd_conta
		dataType: string
		lineageTag: 1d0259b6-9944-43b3-bebf-0e8d2cc94615
		summarizeBy: none
		sourceColumn: cd_conta

		annotation SummarizationSetBy = Automatic

	column vlr_lancamento
		dataType: double
		lineageTag: f52276bd-9558-49d7-9be1-bdbc7266ce00
		summarizeBy: sum
		sourceColumn: vlr_lancamento

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fat_livro_caixa = m
		mode: import
		source =
				let
				    Fonte = PowerPlatform.Dataflows(null),
				    Workspaces = Fonte{[Id="Workspaces"]}[Data],
				    #"3302bffe-37e3-48cf-8e61-0e1eba5f63ce" = Workspaces{[workspaceId="3302bffe-37e3-48cf-8e61-0e1eba5f63ce"]}[Data],
				    #"0e903939-a26b-42c1-9cc2-baebc4f5b136" = #"3302bffe-37e3-48cf-8e61-0e1eba5f63ce"{[dataflowId="0e903939-a26b-42c1-9cc2-baebc4f5b136"]}[Data],
				    fat_estoques_ = #"0e903939-a26b-42c1-9cc2-baebc4f5b136"{[entity="fat_livro_caixa",version=""]}[Data],
				    #"Tipo Alterado1" = Table.TransformColumnTypes(fat_estoques_,{{"dt_lancamento", type date}, {"hr_lancamento", type time}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado1",{{"codContasCaixa", "cd_conta"}, {"valor", "vlr_lancamento"}})
				in
				    #"Colunas Renomeadas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

