table 'Produtos Convert'
	lineageTag: 766b0265-0bf6-4a2a-9cbc-420f10901427

	column Peso
		dataType: double
		lineageTag: ee699771-216c-4401-9a10-7aaa2e0874ab
		summarizeBy: sum
		sourceColumn: Peso

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CustoUnitárioConvertido
		dataType: double
		lineageTag: 87800164-73e2-48ab-a0f5-bf243259117e
		summarizeBy: sum
		sourceColumn: CustoUnitárioConvertido

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column status
		dataType: string
		lineageTag: 0d6a0e1a-d02d-42f8-b159-3c058587426a
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column id_produto
		dataType: string
		lineageTag: 139b0525-46c0-41f5-8f15-a457a4f18223
		summarizeBy: none
		sourceColumn: id_produto

		annotation SummarizationSetBy = Automatic

	column UndOriginal
		dataType: string
		lineageTag: 31be37ab-6386-4f3b-9102-79da117d268b
		summarizeBy: none
		sourceColumn: UndOriginal

		annotation SummarizationSetBy = Automatic

	column UndFinal
		dataType: string
		lineageTag: d1a0e026-8292-4490-b0e7-b82b2fa91e6c
		summarizeBy: none
		sourceColumn: UndFinal

		annotation SummarizationSetBy = Automatic

	column ValorCompra
		dataType: double
		lineageTag: 62f1a58f-3214-4dd3-be71-e9ff5a5bedfb
		summarizeBy: sum
		sourceColumn: ValorCompra

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CustoUnitário
		dataType: double
		lineageTag: 8026c3a6-ef42-40c4-b8c8-ffc02de11363
		summarizeBy: sum
		sourceColumn: CustoUnitário

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sistema
		dataType: string
		lineageTag: 1ca902cc-bde7-4330-8969-99a4fa1c698c
		summarizeBy: none
		sourceColumn: sistema

		annotation SummarizationSetBy = Automatic

	column produto
		dataType: int64
		formatString: 0
		lineageTag: faca3c30-c016-4dda-94e3-257a4e2c6b15
		summarizeBy: sum
		sourceColumn: produto

		annotation SummarizationSetBy = Automatic

	column ordem_venda
		dataType: string
		lineageTag: e4c01bd7-787c-40d1-959a-be86e5914c7c
		summarizeBy: none
		sourceColumn: ordem_venda

		annotation SummarizationSetBy = Automatic

	column fornecedor
		dataType: string
		lineageTag: a35c25be-2469-4760-8945-c7ffe904f1b9
		summarizeBy: none
		sourceColumn: fornecedor

		annotation SummarizationSetBy = Automatic

	column Descrição
		dataType: string
		lineageTag: 2705521e-1f01-4eef-9520-6e3ddd031441
		summarizeBy: none
		sourceColumn: Descrição

		annotation SummarizationSetBy = Automatic

	column quantidade
		dataType: double
		lineageTag: 316fda89-e2b7-4bd5-959b-7484173aeb28
		summarizeBy: sum
		sourceColumn: quantidade

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column qtd_convert
		dataType: double
		lineageTag: 538a85c0-af9e-48d5-bc1d-ab43858c2cea
		summarizeBy: sum
		sourceColumn: qtd_convert

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column dt_prev_recebimento
		dataType: dateTime
		formatString: Short Date
		lineageTag: d0dcb625-14b4-4e00-b390-907ad411ae79
		summarizeBy: none
		sourceColumn: dt_prev_recebimento

		variation Variation
			isDefault
			relationship: 91b51797-63ff-4ccf-936c-d9ad54c37de6
			defaultHierarchy: LocalDateTable_70ca9f36-df9d-489f-b40a-7bef05cef57e.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column dt_pedido
		dataType: dateTime
		formatString: Short Date
		lineageTag: 69ce1eea-3145-4f83-9486-8a2728b9d899
		summarizeBy: none
		sourceColumn: dt_pedido

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column mesclado
		dataType: string
		lineageTag: 46d79925-99ee-46dc-8579-342d7a2347aa
		summarizeBy: none
		sourceColumn: mesclado

		annotation SummarizationSetBy = Automatic

	column QuantidadeRecebida
		dataType: string
		lineageTag: b7afeec6-6ac3-4b3d-a0af-8a3d2b3f56d0
		summarizeBy: none
		sourceColumn: QuantidadeRecebida

		annotation SummarizationSetBy = Automatic

	column SaldoaReceber
		dataType: double
		lineageTag: d0e47f8e-6060-4bb1-9352-29c983e58c12
		summarizeBy: sum
		sourceColumn: SaldoaReceber

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DataRecebimentodoPedido
		dataType: dateTime
		formatString: Short Date
		lineageTag: 98b1fb8c-df8b-4a02-80ac-b96facf804cd
		summarizeBy: none
		sourceColumn: DataRecebimentodoPedido

		variation Variation
			isDefault
			relationship: 584fd3a3-feee-4597-9a99-33d93863f6e0
			defaultHierarchy: LocalDateTable_72195b58-743f-4cb9-8e19-e40505c2a90f.'Hierarquia de datas'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Diferenca Dias' =
			
			IF('Produtos Convert'[DataRecebimentodoPedido] > 0,
			   'Produtos Convert'[dt_pedido] - 'Produtos Convert'[DataRecebimentodoPedido],
			   BLANK())
		dataType: int64
		formatString: 0
		lineageTag: 6d8398c9-6c84-49ff-9776-19ae988bdeef
		summarizeBy: sum

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column produtos_convert_saldo = 'Produtos Convert'[SaldoaReceber]/'Produtos Convert'[Peso]
		lineageTag: aa94f30f-01d3-4c8b-a663-49f418ef6759
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column saldo_a_receber_cvt = 'Produtos Convert'[SaldoaReceber]*'Produtos Convert'[Peso]
		lineageTag: 100b1e53-4f0b-4ee4-9623-640336a5c3b6
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ID_Espelho
		dataType: string
		lineageTag: 5b3eb80a-7f0a-4bdf-b1db-577ebc303b34
		summarizeBy: none
		sourceColumn: ID_Espelho

		annotation SummarizationSetBy = Automatic

	column ID_Espelhado
		dataType: string
		lineageTag: e00c7779-8ef8-4e1e-b33f-89af0563b175
		summarizeBy: none
		sourceColumn: ID_Espelhado

		annotation SummarizationSetBy = Automatic

	partition 'Produtos Convert' = m
		mode: import
		source =
				let
				    Fonte = SharePoint.Tables("https://ypbi.sharepoint.com/sites/AcoNorte2", [Implementation=null, ApiVersion="Auto"]),
				    #"eeff6f52-9c2f-4d52-8216-e45a9b58bddc" = Fonte{[Id="eeff6f52-9c2f-4d52-8216-e45a9b58bddc"]}[Items],
				    #"Colunas Renomeadas" = Table.RenameColumns(#"eeff6f52-9c2f-4d52-8216-e45a9b58bddc",{{"ID", "ID.1"}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Colunas Renomeadas",{"FileSystemObjectType", "Id", "ServerRedirectedEmbedUri", "ServerRedirectedEmbedUrl", "ContentTypeId", "Title", "OData__ColorTag", "ComplianceAssetId"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Removidas",{{"Peso", type number}}),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Tipo Alterado",{"OData_﻿Sistema", "Peso", "Cód Produto", "Descrição", "Ordem de Compra", "Fornecedor", "Und Original", "Und Final", "Peso Compra", "Valor Compra", "Qtd Convert", "Custo Unitário", "Custo Unitário_x0020", "Status", "Data Prev Recebiment", "Data Pedido", "ID Produto", "Mesclado", "ID.1", "Modified", "Created", "AuthorId", "EditorId", "OData__UIVersionString", "Attachments", "GUID", "FirstUniqueAncestorSecurableObject", "RoleAssignments", "AttachmentFiles", "ContentType", "GetDlpPolicyTip", "FieldValuesAsHtml", "FieldValuesAsText", "FieldValuesForEdit", "File", "Folder", "LikedByInformation", "ParentList", "Properties", "Versions", "Author", "Editor"}),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Colunas Reordenadas",{{"Fornecedor", "fornecedor"}}),
				    #"Colunas Reordenadas1" = Table.ReorderColumns(#"Colunas Renomeadas1",{"OData_﻿Sistema", "Peso", "Und Original", "Cód Produto", "Descrição", "Ordem de Compra", "fornecedor", "Und Final", "Peso Compra", "Valor Compra", "Qtd Convert", "Custo Unitário", "Custo Unitário_x0020", "Status", "Data Prev Recebiment", "Data Pedido", "ID Produto", "Mesclado", "ID.1", "Modified", "Created", "AuthorId", "EditorId", "OData__UIVersionString", "Attachments", "GUID", "FirstUniqueAncestorSecurableObject", "RoleAssignments", "AttachmentFiles", "ContentType", "GetDlpPolicyTip", "FieldValuesAsHtml", "FieldValuesAsText", "FieldValuesForEdit", "File", "Folder", "LikedByInformation", "ParentList", "Properties", "Versions", "Author", "Editor"}),
				    #"Colunas Renomeadas2" = Table.RenameColumns(#"Colunas Reordenadas1",{{"Und Original", "UndOriginal"}}),
				    #"Colunas Reordenadas2" = Table.ReorderColumns(#"Colunas Renomeadas2",{"OData_﻿Sistema", "Peso", "UndOriginal", "Valor Compra", "Cód Produto", "Descrição", "Ordem de Compra", "fornecedor", "Und Final", "Peso Compra", "Qtd Convert", "Custo Unitário", "Custo Unitário_x0020", "Status", "Data Prev Recebiment", "Data Pedido", "ID Produto", "Mesclado", "ID.1", "Modified", "Created", "AuthorId", "EditorId", "OData__UIVersionString", "Attachments", "GUID", "FirstUniqueAncestorSecurableObject", "RoleAssignments", "AttachmentFiles", "ContentType", "GetDlpPolicyTip", "FieldValuesAsHtml", "FieldValuesAsText", "FieldValuesForEdit", "File", "Folder", "LikedByInformation", "ParentList", "Properties", "Versions", "Author", "Editor"}),
				    #"Colunas Renomeadas3" = Table.RenameColumns(#"Colunas Reordenadas2",{{"Valor Compra", "ValorCompra"}}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Colunas Renomeadas3",{{"UndOriginal", type text}}),
				    #"Colunas Renomeadas4" = Table.RenameColumns(#"Tipo Alterado1",{{"Und Final", "UndFinal"}}),
				    #"Colunas Reordenadas3" = Table.ReorderColumns(#"Colunas Renomeadas4",{"OData_﻿Sistema", "Peso", "UndOriginal", "UndFinal", "ValorCompra", "Cód Produto", "Descrição", "Ordem de Compra", "fornecedor", "Peso Compra", "Qtd Convert", "Custo Unitário", "Custo Unitário_x0020", "Status", "Data Prev Recebiment", "Data Pedido", "ID Produto", "Mesclado", "ID.1", "Modified", "Created", "AuthorId", "EditorId", "OData__UIVersionString", "Attachments", "GUID", "FirstUniqueAncestorSecurableObject", "RoleAssignments", "AttachmentFiles", "ContentType", "GetDlpPolicyTip", "FieldValuesAsHtml", "FieldValuesAsText", "FieldValuesForEdit", "File", "Folder", "LikedByInformation", "ParentList", "Properties", "Versions", "Author", "Editor"}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Colunas Reordenadas3",{{"UndFinal", type text}, {"ValorCompra", type number}}),
				    #"Colunas Renomeadas5" = Table.RenameColumns(#"Tipo Alterado2",{{"Custo Unitário", "CustoUnitário"}}),
				    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Colunas Renomeadas5",{{"CustoUnitário", type number}}),
				    #"Colunas Reordenadas4" = Table.ReorderColumns(#"Tipo Alterado3",{"OData_﻿Sistema", "Peso", "UndOriginal", "UndFinal", "ValorCompra", "CustoUnitário", "Cód Produto", "Descrição", "Ordem de Compra", "fornecedor", "Peso Compra", "Qtd Convert", "Custo Unitário_x0020", "Status", "Data Prev Recebiment", "Data Pedido", "ID Produto", "Mesclado", "ID.1", "Modified", "Created", "AuthorId", "EditorId", "OData__UIVersionString", "Attachments", "GUID", "FirstUniqueAncestorSecurableObject", "RoleAssignments", "AttachmentFiles", "ContentType", "GetDlpPolicyTip", "FieldValuesAsHtml", "FieldValuesAsText", "FieldValuesForEdit", "File", "Folder", "LikedByInformation", "ParentList", "Properties", "Versions", "Author", "Editor"}),
				    #"Colunas Removidas1" = Table.RemoveColumns(#"Colunas Reordenadas4",{"ID.1", "Modified", "Created", "AuthorId", "EditorId", "OData__UIVersionString", "Attachments", "GUID", "FirstUniqueAncestorSecurableObject", "RoleAssignments", "AttachmentFiles", "ContentType", "GetDlpPolicyTip", "FieldValuesAsHtml", "FieldValuesAsText", "FieldValuesForEdit", "File", "Folder", "LikedByInformation", "ParentList", "Properties", "Versions", "Author", "Editor"}),
				    #"Colunas Renomeadas6" = Table.RenameColumns(#"Colunas Removidas1",{{"OData_﻿Sistema", "sistema"}}),
				    #"Tipo Alterado4" = Table.TransformColumnTypes(#"Colunas Renomeadas6",{{"sistema", type text}}),
				    #"Colunas Reordenadas5" = Table.ReorderColumns(#"Tipo Alterado4",{"Peso", "UndOriginal", "UndFinal", "ValorCompra", "CustoUnitário", "Cód Produto", "Descrição", "Ordem de Compra", "sistema", "fornecedor", "Peso Compra", "Qtd Convert", "Custo Unitário_x0020", "Status", "Data Prev Recebiment", "Data Pedido", "ID Produto", "Mesclado"}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Colunas Reordenadas5", "CustoUnitárioConvertido", each [ValorCompra]/[Qtd Convert]),
				    #"Tipo Alterado5" = Table.TransformColumnTypes(#"Personalização Adicionada",{{"CustoUnitárioConvertido", type number}, {"Status", type text}}),
				    #"Colunas Renomeadas7" = Table.RenameColumns(#"Tipo Alterado5",{{"Cód Produto", "produto"}}),
				    #"Tipo Alterado6" = Table.TransformColumnTypes(#"Colunas Renomeadas7",{{"produto", Int64.Type}}),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Tipo Alterado6", "id_produto", each Text.From([produto]) & Text.From([sistema])),
				    #"Colunas Removidas2" = Table.RemoveColumns(#"Personalização Adicionada1",{"ID Produto"}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Colunas Removidas2"," ","",Replacer.ReplaceText,{"Mesclado"}),
				    #"Colunas Reordenadas6" = Table.ReorderColumns(#"Valor Substituído",{"Peso", "UndOriginal", "UndFinal", "ValorCompra", "CustoUnitário", "CustoUnitárioConvertido", "Status", "id_produto", "Mesclado", "sistema", "produto", "Descrição", "Ordem de Compra", "fornecedor", "Peso Compra", "Qtd Convert", "Custo Unitário_x0020", "Data Prev Recebiment", "Data Pedido"}),
				    #"Colunas Renomeadas8" = Table.RenameColumns(#"Colunas Reordenadas6",{{"Ordem de Compra", "ordem_venda"}}),
				    #"Colunas Reordenadas7" = Table.ReorderColumns(#"Colunas Renomeadas8",{"Peso", "UndOriginal", "UndFinal", "ValorCompra", "CustoUnitário", "CustoUnitárioConvertido", "Status", "id_produto", "Mesclado", "sistema", "produto", "ordem_venda", "fornecedor", "Descrição", "Peso Compra", "Qtd Convert", "Custo Unitário_x0020", "Data Prev Recebiment", "Data Pedido"}),
				    #"Tipo Alterado7" = Table.TransformColumnTypes(#"Colunas Reordenadas7",{{"ordem_venda", type text}, {"fornecedor", type text}, {"id_produto", type text}}),
				    #"Colunas Renomeadas9" = Table.RenameColumns(#"Tipo Alterado7",{{"Peso Compra", "quantidade"}, {"Qtd Convert", "qtd_convert"}}),
				    #"Tipo Alterado8" = Table.TransformColumnTypes(#"Colunas Renomeadas9",{{"Descrição", type text}, {"quantidade", type number}, {"qtd_convert", type number}}),
				    #"Colunas Renomeadas10" = Table.RenameColumns(#"Tipo Alterado8",{{"Data Pedido", "dt_pedido"}, {"Data Prev Recebiment", "dt_prev_recebimento"}}),
				    #"Tipo Alterado9" = Table.TransformColumnTypes(#"Colunas Renomeadas10",{{"dt_pedido", type date}, {"dt_prev_recebimento", type date}}),
				    #"Colunas Removidas3" = Table.RemoveColumns(#"Tipo Alterado9",{"Custo Unitário_x0020", "Mesclado"}),
				    #"Personalização Adicionada2" = Table.AddColumn(#"Colunas Removidas3", "mesclado", each Text.From([produto]) & Text.From([ordem_venda]) & Text.From([Status])),
				    #"Colunas Renomeadas11" = Table.RenameColumns(#"Personalização Adicionada2",{{"Status", "status"}})
				in
				    #"Colunas Renomeadas11"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

